# Generated by Django 4.2.6 on 2023-10-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='reservations',
        ),
    ]
